apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jayfray12-poi-map-app-dev
  annotations:
    argocd/app-name: jayfray12-poi-map-app-dev
    backstage.io/kubernetes-id: jayfray12-poi-map-app-dev
    backstage.io/kubernetes-namespace: jayfray12
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=jayfray12-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23JanusN/jayfray12-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/jayfray12/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.summit23bis.17gd.p1.openshiftapps.com/k8s/ns/jayfray12/deployments/poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.summit23bis.17gd.p1.openshiftapps.com/#https://github.com/Summit23JanusN/jayfray12-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:jayfray12"
  system: workshop-system-jayfray12
  consumesApis:
    - gateway-api-jayfray12
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-jayfray12
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:jayfray12"
